version: "3.8"
services:
  backend:
    image: "erenof79/springboot-react-fullstack:5.1.2023.20.7.50"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev